## Reg smoothing loss

CE + MSE - l_ij * ( target_t - pred_t) * log(p)

In [1]:
import torch

In [2]:
diag_t = torch.Tensor([1,2,3,-2,4])
target = torch.Tensor([0, 1, 0, 1, 1])

In [3]:
diag_t * target

tensor([ 0.,  2.,  0., -2.,  4.])

In [31]:
index = ((target == 1) & (diag_t < 0)).nonzero()

In [33]:
diag_t[index] = target[index]
print (diag_t)

tensor([1., 2., 3., 1., 4.])


In [4]:
diag_t[(diag_t <= 0).nonzero()] = 0

In [36]:
0.1 * torch.mean(diag_t * diag_t)

tensor(0.6200)

In [27]:
dia = torch.max(diag_t, torch.zeros(5))

In [28]:
dia

tensor([1., 2., 3., 0., 4.])